version: '3.8'

services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app   
    # networks:
    #   - blockchain-network