version: '3'
services:
  blockchain-root:
    build: .
    ports:
      - "3001:3000"  # Maps host port 3001 to container port 3000 for the first instance
    environment:
      - PORT=3000
      - IP=blockchain-root
      - USER_DB=mongodb:27017
      - BLOCK_DB=mongodb:27017/root
      - NUM_REPLICAS=1
    networks:
      - blockchain-network

  blockchain1:
    build: .
    ports:
      - "3002:3000"  
    environment:
      - ROOT_IP=blockchain-root  
      - ROOT_PORT=3000
      - IP=blockchain1
      - PORT=3000
      - BLOCK_DB=mongodb:27017/block1_test
      - USER_DB=mongodb:27017
    networks:
      - blockchain-network

  blockchain2:
    build: .
    ports:
      - "3003:3000" 
    environment:
      - ROOT_IP=blockchain-root  
      - ROOT_PORT=3000
      - IP=blockchain2
      - PORT=3000
      - BLOCK_DB=mongodb:27017/block2_test
      - USER_DB=mongodb:27017
    networks:
      - blockchain-network

  # blockchain-remote:
  #   build: .
  
  mongodb:
    image: mongo
    ports:
      - "27017:27017"  # Maps host port 27017 to container port 27017 for MongoDB
    networks:
      - blockchain-network
    volumes:
      - /Users/jjoyce/Programming/Distributed/FinalProject/p4-final-cool-team-1/blockchain/mongod.conf

networks:
  blockchain-network:
    driver: bridge
  